#==============================================================================
# DEPENDENCY UPDATES
#==============================================================================

version: 2

#==============================================================================
# GITHUB ACTION UPDATES
#==============================================================================

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    groups:
      github-actions:
        patterns:
          - "*"

#==============================================================================
# TERRAFORM PROVIDER UPDATES
#==============================================================================

  - package-ecosystem: terraform
    directories:
      - /compute-instance
      - /identity-compartment
      - /object-storage-bucket
      - /vcn
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Etc/UTC
    groups:
      terraform-providers:
        patterns:
          - "*"